print('Hello in our Application to know what is your channal name and the number of letters in your name ') 
print()
user_name=input('what is your nickname ? \n ')
print()
channal=input('What is your channal about ? \n ')
print()
print('you could your channal is \n  ' + (channal )+ " with "+ (user_name))
print()
print('The number of letters in your name is ')
print(len(user_name))
